package com.mulesoft.log4j2.xray;

import org.apache.logging.log4j.LogManager;

public class LoggingTester {
	public static void main(String[] args) {
		System.setProperty("correlationId", "ef1204a0-7cd0-11ec-ae64-068df25f14c6");
		LogManager.getLogger().info("{\n"
				+ "    \"correlationId\": \"f39e6a90-7cd0-11ec-9cda-0679e83acb76\",\n"
				+ "    \"message\": \"response\",\n"
				+ "    \"tracePoint\": \"START\",\n"
				+ "    \"priority\": \"INFO\",\n"
				+ "    \"elapsed\": 629,\n"
				+ "    \"locationInfo\": {\n"
				+ "        \"lineInFile\": \"26\",\n"
				+ "        \"component\": \"json-logger:logger\",\n"
				+ "        \"fileName\": \"interface.xml\",\n"
				+ "        \"rootContainer\": \"s-azure-api-main\"\n"
				+ "    },\n"
				+ "    \"timestamp\": \"2022-01-24T04:49:03.055Z\",\n"
				+ "    \"content\": {\n"
				+ "        \"payload\": [\n"
				+ "            {\n"
				+ "                \"id\": \"cb74c367-c6b0-4e11-99dd-173c51e4c1b5\",\n"
				+ "                \"name\": \"INSIGHT-STUDIO\",\n"
				+ "                \"description\": \"INSIGHT-STUDIO\",\n"
				+ "                \"dynamic\": {\n"
				+ "                    \"userTag\": \"INS:studio\"\n"
				+ "                }\n"
				+ "            }\n"
				+ "        ]\n"
				+ "    },\n"
				+ "    \"applicationName\": \"s-azure-api\",\n"
				+ "    \"applicationVersion\": \"1.0.0\",\n"
				+ "    \"environment\": \"sandbox\",\n"
				+ "    \"threadName\": \"[MuleRuntime].uber.21: [s-azure-api-sandbox-ia].s-azure-api-main.BLOCKING @671d4dfb\"\n"
				+ "}");
		LogManager.getLogger().info("{\n"
				+ "    \"correlationId\": \"f39e6a90-7cd0-11ec-9cda-0679e83acb76\",\n"
				+ "    \"message\": \"response\",\n"
				+ "    \"tracePoint\": \"END\",\n"
				+ "    \"priority\": \"INFO\",\n"
				+ "    \"elapsed\": 629,\n"
				+ "    \"locationInfo\": {\n"
				+ "        \"lineInFile\": \"26\",\n"
				+ "        \"component\": \"json-logger:logger\",\n"
				+ "        \"fileName\": \"interface.xml\",\n"
				+ "        \"rootContainer\": \"s-azure-api-main\"\n"
				+ "    },\n"
				+ "    \"timestamp\": \"2022-01-24T04:49:03.055Z\",\n"
				+ "    \"content\": {\n"
				+ "        \"payload\": [\n"
				+ "            {\n"
				+ "                \"id\": \"cb74c367-c6b0-4e11-99dd-173c51e4c1b5\",\n"
				+ "                \"name\": \"INSIGHT-STUDIO\",\n"
				+ "                \"description\": \"INSIGHT-STUDIO\",\n"
				+ "                \"dynamic\": {\n"
				+ "                    \"userTag\": \"INS:studio\"\n"
				+ "                }\n"
				+ "            }\n"
				+ "        ]\n"
				+ "    },\n"
				+ "    \"applicationName\": \"s-azure-api\",\n"
				+ "    \"applicationVersion\": \"1.0.0\",\n"
				+ "    \"environment\": \"sandbox\",\n"
				+ "    \"threadName\": \"[MuleRuntime].uber.21: [s-azure-api-sandbox-ia].s-azure-api-main.BLOCKING @671d4dfb\"\n"
				+ "}");
	}
}
